config/routes.rb
Rails.application.routes.draw do

  get 'expenses/index'

  root 'pages#main'

  devise_for :users

  match '/incomes', to: 'incomes#index', via: 'get'
  match '/incomes', to: 'incomes#create', via: 'post'

  resources :categories

  resources :cash, except: [:create]
  match '/cashes', to: 'cash#create', via: 'post'

  resources :expenses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash.rb
class Cash < ApplicationRecord
  validates :value,       presence: true, length: { maximum: 50 }
  validates :category_id, presence: true

  belongs_to :category
  has_many   :expenses
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title,   presence: true, length: { maximum: 50 }
  validates :user_id, presence: true

  belongs_to :user

  has_one :cash,      dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :value,       presence: true
  validates :category_id, presence: true
  validates :cash_id,     presence: true


  belongs_to :category
  belongs_to :cash
end

app/models/income.rb
class Income < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :value, presence: true
  validates :date,  presence: true

  belongs_to :user

  scope :sort_with_date, -> (direction){ order(date: direction) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :incomes ,   dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :expenses,   dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!


end

app/controllers/cash_controller.rb
class CashController < ApplicationController

  def create
    cash = Cash.new(cash_params)

    if cash.save
      flash[:success] = "You planned #{cash.value.to_s} $ for this category"
      redirect_to cash.category
    else
      flash.now[:danger] = "Fill sash field, please!"
      redirect_to Category.find(params[:category_id])
    end

  end

  def update
    cash = Cash.find(params[:id])

    if cash.update_attributes(cash_params)
      flash[:success] = "You planned #{cash.value.to_s} $ for this category"
      redirect_to cash.category
    else
      flash.now[:danger] = "Fill cash field, please!"
      redirect_to Category.find(params[:category_id])
    end

  end

  private

  def cash_params
    params.require(:cash).permit(:value, :category_id)
  end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = current_user.categories.page(params[:page]).per(6)
    @category   = current_user.categories.new
  end

  def show
    @category = Category.find(params[:id])

    if @category.cash
      @cash = @category.cash
    else
      @cash = Cash.new
    end

    @expense  = Expense.new
    @expenses = @category.expenses.order(date: 'DESC').page(params[:page]).per(6)
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(category_params)
      flash[:success] = "Category was renamed"
      redirect_to @category
    else
      flash[:danger] = "Category not updated"
      redirect_to @category
    end
  end


  def create
    category = current_user.categories.new(category_params)

    if category.save
      flash.now[:success] = "Category was created"
      @categories = current_user.categories.page(params[:page]).per(6)
    else
      flash[:danger] = "Fill category field, please!"
      redirect_to categories_path
    end

  end

  def destroy
    category = Category.find(params[:id])

    if category.destroy
      @categories = current_user.categories.page(params[:page]).per(6)
    else
      flash.now[:danger] = "Category is not removed!"
      redirect_to categories_path
    end

  end

  private

  def category_params
    params.require(:category).permit(:title)
  end 

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses   = current_user.expenses
    @expenses   = @expenses.where(category_id: params[:category_id]) if params[:category_id].present?
    @expenses   = @expenses.page(params[:page]).per(6)
    @categories = current_user.categories
  end


  def create
    expense  = current_user.expenses.new(expense_params)
    cash = Cash.find(expense.cash_id)
    category = Category.find(expense.category_id)

    if expense.value <= cash.value
      if expense.save 
        cash.value = cash.value - expense.value
        if cash.value == 0
          cash.save
          flash[:success] = "You can buy #{expense.category.title}!"
          redirect_to category
        else cash.value > 0
          cash.save 
          flash[:success] = "You still have to buy #{expense.cash.value} $!"
          redirect_to category
        end
      else 
        flash[:danger] = "Fill expense field, please!"
        redirect_to category
      end
    else
      flash[:danger] = "Expense value more then cash!"
      redirect_to category
    end

  end

  private

  def expense_params
    params.require(:expense).permit(:value, :category_id, :cash_id, :date)
  end 

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
    @direction ||= "DESC"
    @direction = params[:date] if params[:date].present? and params[:date] != ""


    @incomes = current_user.incomes.order(date: @direction).page(params[:page]).per(6)
    @income  = Income.new

  end

  def create

    income = current_user.incomes.new(income_params)

    if income.save
      flash.now[:success] = "Category was created"
      @incomes = current_user.incomes.page(params[:page]).per(6)
    else
      flash[:danger] = "Fill all fields, please!"
      redirect_to incomes_path
    end

  end


  private

  def income_params
    params.require(:income).permit(:title, :value, :date)
  end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    @categories = current_user.categories.page(params[:page]).per(6) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def all_cash_incomes
    incomes  = current_user.incomes.inject(0) {|sum,elem| sum += elem.value } if current_user.incomes
    expenses = current_user.expenses.inject(0) {|sum,elem| sum += elem.value } if current_user.expenses
    incomes - expenses
  end

  def all_cash
    result = 0
    if current_user.categories
      current_user.categories.each do |elem| 
        if elem.cash
          result += elem.cash.value 
        end
      end
    end
    result
  end

  def check_balance
    if all_cash_incomes > all_cash
      (all_cash_incomes - all_cash).to_s + ' $' 
    else
      'No money for planning!'
    end
  end

  def calculate_expenses(category)
    category.expenses.inject(0) {|sum,elem| sum += elem.value}
  end

end

app/helpers/cash_helper.rb
module CashHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper



end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cash/_cash_form.slim
    div class="form_income"
      div class="col-md-4 col-md-offset-4"
          = simple_form_for @cash, remote: true  do |f| 
            = f.input :value, label: false , placeholder: 'cash'
            = f.hidden_field :category_id, id: 'hidden_category', value: @category.id
            = f.button :submit , "Set cash" 

app/views/categories/_cash_update_form.slim
      = simple_form_for @category, :method => :put, remote: true  do |f| 
        = f.input :title, label: false , placeholder: 'Rename category'
        = f.button :submit , "Rename category"

app/views/categories/_categories_table.slim
- if !@categories.empty?
  div class="table-title"
    div class="container-fluid"
      table class="table-fill"
        thead
        tr
          th class="text-left" Categories
          th 
        tbody class="table-hover"
        - @categories.each do |category|
          tr class="category_row"
            td class="text-left" = category.title
            td class="text-left" 
              = link_to "View", category_path(category.id), class:"links_inline"
              = link_to "Delete", category_path(category.id), :method => :delete, :confirm => "Are you sure?", :remote => true, class:"links_inline"


dev class="col-md-12 text-center"
  = paginate @categories 

app/views/categories/create.js.erb
$("#categories_table").html("<%= escape_javascript(render 'categories_table.slim' ) %>");

app/views/categories/destroy.js.erb
$("#categories_table").html("<%= escape_javascript(render 'categories_table.slim' ) %>");

app/views/categories/index.slim
div class="container-fluid"
  = render "shared/flash_errors"
  div class="container-fluid text-center"
    h3 Create Category
  div class="form_income"
    div class="col-md-4 col-md-offset-4"
      = simple_form_for @category, remote: true do |f| 
        = f.input :title, label: false , placeholder: 'Title'
        = f.button :submit 

div id="categories_table"
  = render "categories/categories_table"

app/views/categories/show.slim
div class="container-fluid text-center"
  = render "shared/flash_errors"
  h2 = @category.title 
  div id="rename_form" class="form_links" onclick="showCashForm('category_name');" Rename category
  div id="category_name" style="display:none;"
    div class="form_income"
      div class="col-md-4 col-md-offset-4"
        = render "categories/cash_update_form"


div class="container-fluid text-center"
  -if @cash.value == nil
    h3 Planning money for this category, please!
    = render "cash/cash_form"
  -else
    h3 = "Planning "+ @cash.value.to_s + " $"
    div class="form_links" onclick="showCashForm('cash_form');" Change cash value
    div id="cash_form" style="display:none;"
      = render "cash/cash_form"

-if @cash.value
  div class="container-fluid text-center"
    h3 Make spending!
    = render "expenses/expense_form"

div id="income_table"
  = render "expenses/expenses_table"

app/views/expenses/_expense_form.slim
    div class="form_income"
      div class="col-md-4 col-md-offset-4"
          = simple_form_for @expense, remote: true  do |f| 
            = f.input :value, label: false , placeholder: 'Expense value!'
            = f.input :date, label: false , order: [:day, :month, :year], placeholder:'Expense date'
            = f.hidden_field :category_id, value: @category.id
            = f.hidden_field :cash_id, value: @cash.id
            = f.button :submit , "Save expense" 

app/views/expenses/_expenses_index_table.slim
- if !@expenses.empty?
  div class="table-title"
    div class="container-fluid"
      table class="table-fill"
        thead
        tr
          th class="text-left" Expense value
          th class="text-left" Expense category
          th class="text-left" Expense date
        tbody class="table-hover"
        - @expenses.each do |expense|
          tr
            td class="text-left rows" = expense.value.to_s + ' $'
            td class="text-left rows" = Category.find(expense.category_id).title
            td class="text-left rows" = expense.date

app/views/expenses/_expenses_table.slim
- if !@expenses.empty?
  div class="table-title"
    div class="container-fluid"
      table class="table-fill"
        thead
        tr
          th class="text-left" Expense value
          th class="text-left" Expense date
        tbody class="table-hover"
        - @expenses.each do |expense|
          tr class="expense_row"
            td class="text-left" = expense.value.to_s + ' $'
            td class="text-left" = expense.date

app/views/expenses/_select_category.slim
div class="form_income"
  = form_tag("/expenses", method: 'get', id:"category_select_form",  remote: :true)
    = select_tag(:category_id, options_from_collection_for_select(@categories, :id, :title), id:"expense_category")



javascript:

  $('#expense_category').change(function(e) {
    $('#category_select_form').submit();
  });

app/views/expenses/index.js.erb
$("#expense_table").html("<%= escape_javascript(render 'expenses_index_table.slim' ) %>");

app/views/expenses/index.slim
div class="container-fluid text-center"
  h3 Select Category
  = render "expenses/select_category"

div id="expense_table"
  = render "expenses/expenses_index_table"

  div class="col-md-12 text-center"
    = paginate @expenses 

app/views/incomes/_income_table.slim
- if !@incomes.empty?
  div class="table-title"
    div class="container-fluid"
      table class="table-fill"
        thead
        tr
          th class="text-left" Income title
          th class="text-left" Income value
          th class="text-left" 
            span Date:
            = form_tag("/incomes", method: 'get', id:"date_form",  remote: :true, style:"display: inline;")
              = select_tag(:date, options_for_select([['Last', 'DESC'],['Old', 'ASC']],@direction), id:"income_date_direction")
        tbody class="table-hover"
        - @incomes.each do |income|
          tr class="income_row"
            td class="text-left" = income.title
            td class="text-left" = income.value.to_s + ' $'
            td class="text-left" = income.date

javascript:

  $('#income_date_direction').change(function(e) {
    $('#date_form').submit();
  });

app/views/incomes/create.js.erb
$("#income_table").html("<%= escape_javascript(render 'income_table.slim' ) %>");

app/views/incomes/index.js.erb
$("#income_table").html("<%= escape_javascript(render 'income_table.slim' ) %>");

app/views/incomes/index.slim
div class="container-fluid"
  = render "shared/flash_errors"
  div class="container-fluid text-center"
    h3 Create income
  div class="form_income"
    div class="col-md-4 col-md-offset-4"
      = simple_form_for @income, remote: true do |f| 
        = f.input :title, label: false , placeholder: 'Title'
        = f.input :value, label: false , placeholder: 'Value'
        = f.input :date, label: false , order: [:day, :month, :year], placeholder:'Income date'
        = f.button :submit , "Create income"

div id="income_table"
  = render "incomes/income_table"

dev class="col-md-12 text-center"
  = paginate @incomes 

app/views/layouts/_menu_bar.slim
header id="menu"
  div class="logo"
    a href="" Budget
  nav
    ul class="side"
      li 
        = link_to "Main", root_path 
      li 
        = link_to "Incomes", incomes_path 
      li
        = link_to "Categorias", categories_path
      li
        = link_to "Expenses", expenses_path
      li 
        = link_to "Sign out", destroy_user_session_path , method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700">
  </head>

  <body>

    <% if current_user.present?  %>
      <%= render "layouts/menu_bar" %>
      <div id="main">
        <section id="content">
          <%= yield %>
        </section>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/pages/_main_categories_table.slim
- if !@categories.empty?
  div class="table-title"
    div class="container-fluid"
      table class="table-fill"
        thead
        tr
          th class="text-left" Categories
          th class="text-left" Planned costs
          th class="text-left" Expenses
        tbody class="table-hover"
        - @categories.each do |category|
          tr
            td class="text-left" = link_to category.title, category_path(category.id)
            td class="text-left" = category.cash.value.to_s + ' $' if category.cash
            td class="text-left" = calculate_expenses(category).to_s + ' $'


dev class="col-md-12 text-center"
  = paginate @categories 

app/views/pages/main.slim
div class="container-fluid"
  div class="col-md-4"
    div class="container text-center main_panel"
      div class="panel panel-primary"
        div class="panel-heading" All Cash
        div class="panel-body" 
          = all_cash_incomes.to_s + ' $' 
  div class="col-md-4"
    div class="container text-center main_panel"
      div class="panel panel-warning"
        div class="panel-heading" Unplanned money
        div class="panel-body" = check_balance
  div class="col-md-4"
    div class="container text-center main_panel"
      div class="panel panel-success"
        div class="panel-heading" Planned money
        div class="panel-body" = all_cash.to_s + ' $'

div id="main_categories_table"
  = render "pages/main_categories_table"

app/views/shared/_flash_errors.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>